services:
  app:
    build:
      context: ./talkhub_backend
    container_name: talkhub_backend
    ports:
      - "8005:8005"
    volumes:
      - ./talkhub_backend/db:/usr/src/app/db
    # networks:
    #   - ag

  frontend:
    build:
      context: ./talkhub_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    # networks:
    #   - ag

networks:
  ag:
    external: true

    

