services:
  app:
    build:
      context: ./talkhub_backend
    container_name: talkhub_backend
    ports:
      - "8004:8004"
    volumes:
      - ./talkhub_backend/db.sqlite3:/usr/src/app/db.sqlite3

  frontend:
    build:
      context: ./talkhub_frontend
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./talkhub_frontend/dist:/talkhub_frontend/dist
