services:
  app:
    build:
      context: ./talkhub_backend
    container_name: talkhub_backend
    ports:
      - "8005:8005"
    volumes:
      - ./talkhub_backend/db.sqlite3:/usr/src/app/db.sqlite3
    networks:
      - ag

  frontend:
    build:
      context: ./talkhub_frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./talkhub_frontend/dist:/talkhub_frontend/dist
    networks:
      - ag

networks:
  ag:
    external: true

    

