services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    ports:
      - 8004:8004
    volumes:
      - ./app:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./talkhub_frontend
    ports:
      - 3000:80
    volumes:
      - ./talkhub_frontend/dist:/talkhub_frontend/dist

volumes:
  postgres_data:
  app:
  mongo_data: