/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BanDto { 
    /**
     * The ban\'s id
     */
    id_ban: number;
    /**
     * The ban\'s reason
     */
    reason: string;
    /**
     * The ban\'s date
     */
    date: string;
    /**
     * The banned user
     */
    id_user: number;
}

