/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommentListItemUserDto { 
    /**
     * The user\'s id
     */
    id_user: number;
    /**
     * The user\'s name
     */
    name: string;
}

