/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReportDto { 
    /**
     * The report\'s reason
     */
    reason: string;
    /**
     * The report\'s date
     */
    date: string;
    /**
     * The report\'s user
     */
    id_user: number;
    /**
     * The report\'s comment
     */
    id_comment: number;
}

