/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateVoteDto { 
    /**
     * The user id
     */
    id_user: number;
    /**
     * The thread id
     */
    id_thread?: number;
    /**
     * The comment id
     */
    id_comment?: number;
    /**
     * The vote type
     */
    type: number;
}

