/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateNotificationDto { 
    /**
     * The notification\'s date
     */
    date: string;
    /**
     * The notification\'s message
     */
    message: string;
    /**
     * The notification\'s user
     */
    id_user: number;
    /**
     * The notification\'s thread
     */
    id_thread: number;
}

