/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModAplicationDto { 
    /**
     * The modaplication\'s id
     */
    id_modaplication: number;
    /**
     * The aplicant\'s id
     */
    id_user: number;
    /**
     * The modaplication\'s date
     */
    date: string;
    /**
     * The aplication\'s reason
     */
    reason: string;
}

