/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileDto { 
    /**
     * The user\'s id
     */
    id: number;
    /**
     * The user\'s email
     */
    email: string;
    /**
     * The time the token was issued
     */
    iat: number;
    /**
     * The time the token expires
     */
    exp: number;
}

