/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportListItemCommentDto } from './reportListItemCommentDto';
import { ReportListItemUserDto } from './reportListItemUserDto';


export interface ReportListItemDto { 
    /**
     * The report\'s id
     */
    id_report: number;
    /**
     * The report\'s reason
     */
    reason: string;
    /**
     * The report\'s date
     */
    date: string;
    /**
     * The report\'s user
     */
    user: ReportListItemUserDto;
    /**
     * The report\'s comment
     */
    comment: ReportListItemCommentDto;
}

