/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThreadListItemUserDto } from './threadListItemUserDto';
import { ThreadListItemCategoryDto } from './threadListItemCategoryDto';


export interface ThreadListItemDto { 
    /**
     * The thread\'s id
     */
    id_thread: number;
    /**
     * The thread\'s publication date
     */
    publication_date: string;
    /**
     * The thread\'s title
     */
    title: string;
    /**
     * The thread\'s content
     */
    content: string;
    /**
     * The thread\'s publication date
     */
    user: ThreadListItemUserDto;
    /**
     * The thread\'s category
     */
    category: ThreadListItemCategoryDto;
}

