/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ThreadUserDto { 
    /**
     * The user\'s id
     */
    id: number;
    /**
     * The user\'s name
     */
    name: string;
    /**
     * The user\'s role
     */
    role: ThreadUserDto.RoleEnum;
}
export namespace ThreadUserDto {
    export type RoleEnum = 'admin' | 'regular' | 'moderator';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Regular: 'regular' as RoleEnum,
        Moderator: 'moderator' as RoleEnum
    };
}


