/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCategoryDto { 
    /**
     * The category\'s name
     */
    name: string;
    /**
     * The category\'s description
     */
    description: string;
}

