/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    /**
     * The user ID
     */
    id: number;
    /**
     * The user name
     */
    name: string;
    /**
     * The user email
     */
    email: string;
    /**
     * The user bio
     */
    bio: string;
    /**
     * The user creation date
     */
    creation_date: string;
    /**
     * The user role
     */
    role: UserDto.RoleEnum;
}
export namespace UserDto {
    export type RoleEnum = 'admin' | 'regular' | 'moderator';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Regular: 'regular' as RoleEnum,
        Moderator: 'moderator' as RoleEnum
    };
}


