/**
 * Talkhub API
 * This is a forum API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VoteListItemDto { 
    /**
     * The vote\'s id
     */
    id_vote: number;
    /**
     * The comment id
     */
    id_comment: number;
    /**
     * The thread\'s id
     */
    id_thread: number;
    /**
     * The user\'s id
     */
    id_user: number;
    /**
     * The vote type
     */
    type: number;
}

